/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loginpage;

import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Nusrat Ali
 */
public class addproduct extends javax.swing.JFrame {

    /**
     * Creates new form addproduct
     */
    public addproduct() {
        initComponents();
    }
    
    
    public void setData(){
        AddProductBll apb = new AddProductBll();
        AddProductDao apd = new AddProductDaoImpl();
        String Name = txtproduct.getText();
        float unitprice;
        int quantity;
        boolean check;
        try{
        apb.setproductname(Name);
        String category = cbcategory.getSelectedItem().toString();
        apb.setcategory(category);
        check = true;
        unitprice = Float.parseFloat(txtprice.getText());
        quantity = Integer.parseInt(txtquantity.getText());
        apb.setunitprice(unitprice);
        apb.setquantity(quantity);
     
        check = true;
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Please Enter numeric value");
            check = false;
        }
        if (check == true){
            apd.productFile(apb);
            JOptionPane.showMessageDialog(this, "Product Registered Successfully....");
            txtproduct.setText(null);
            txtprice.setText(null);
            txtquantity.setText(null);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categorylbl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        productname = new javax.swing.JLabel();
        txtproduct = new javax.swing.JTextField();
        unitprice = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        lblquantity = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        lblsignout = new javax.swing.JLabel();
        lblexit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblquantity1 = new javax.swing.JLabel();
        cbcategory = new javax.swing.JComboBox<>();
        dashboardbtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        categorylbl.setOpaque(false);

        jLabel2.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel2.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Products");
        jLabel2.setOpaque(true);

        productname.setBackground(java.awt.Color.darkGray);
        productname.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        productname.setForeground(new java.awt.Color(255, 255, 255));
        productname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        productname.setText("Product Name");
        productname.setOpaque(true);

        txtproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductActionPerformed(evt);
            }
        });

        unitprice.setBackground(java.awt.Color.darkGray);
        unitprice.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        unitprice.setForeground(new java.awt.Color(255, 255, 255));
        unitprice.setText("Unit Price");
        unitprice.setOpaque(true);

        lblquantity.setBackground(java.awt.Color.darkGray);
        lblquantity.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblquantity.setForeground(new java.awt.Color(255, 255, 255));
        lblquantity.setText("Quantity");
        lblquantity.setOpaque(true);

        lblsignout.setBackground(new java.awt.Color(0, 96, 50));
        lblsignout.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblsignout.setForeground(new java.awt.Color(255, 255, 255));
        lblsignout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsignout.setText("Sign Out");
        lblsignout.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 153, 51), null));
        lblsignout.setOpaque(true);
        lblsignout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsignoutMouseClicked(evt);
            }
        });

        lblexit.setBackground(new java.awt.Color(0, 96, 50));
        lblexit.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblexit.setForeground(new java.awt.Color(255, 255, 255));
        lblexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblexit.setText("Exit");
        lblexit.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 153, 51), null));
        lblexit.setOpaque(true);
        lblexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblexitMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 96, 50));
        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 102, 51), null));
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        lblquantity1.setBackground(java.awt.Color.darkGray);
        lblquantity1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblquantity1.setForeground(new java.awt.Color(255, 255, 255));
        lblquantity1.setText("Category");
        lblquantity1.setOpaque(true);

        cbcategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Vegetables", "Fruits", "Spices", "Other Products" }));

        dashboardbtn.setBackground(new java.awt.Color(0, 96, 50));
        dashboardbtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        dashboardbtn.setForeground(new java.awt.Color(255, 255, 255));
        dashboardbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardbtn.setText("Dashboard");
        dashboardbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 102, 51), null));
        dashboardbtn.setOpaque(true);
        dashboardbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout categorylblLayout = new javax.swing.GroupLayout(categorylbl);
        categorylbl.setLayout(categorylblLayout);
        categorylblLayout.setHorizontalGroup(
            categorylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categorylblLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(categorylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, categorylblLayout.createSequentialGroup()
                        .addComponent(lblquantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(categorylblLayout.createSequentialGroup()
                        .addGroup(categorylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblquantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(unitprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(productname, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(categorylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtproduct)
                            .addComponent(txtprice)
                            .addComponent(txtquantity, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))))
                .addGap(98, 98, 98))
            .addGroup(categorylblLayout.createSequentialGroup()
                .addComponent(dashboardbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(categorylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(categorylblLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(categorylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblsignout, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(categorylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categorylblLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(113, 113, 113))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categorylblLayout.createSequentialGroup()
                            .addComponent(lblexit, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)))))
        );
        categorylblLayout.setVerticalGroup(
            categorylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categorylblLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(70, 70, 70)
                .addGroup(categorylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtproduct)
                    .addComponent(productname, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(categorylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(unitprice, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtprice))
                .addGap(43, 43, 43)
                .addGroup(categorylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(categorylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblquantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(categorylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblexit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsignout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboardbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        getContentPane().add(categorylbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 500, 620));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nusrat Ali\\Desktop\\download (2).jfif")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -150, 680, 1110));

        setBounds(0, 0, 652, 834);
    }// </editor-fold>//GEN-END:initComponents

    private void txtproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductActionPerformed
        // TODO add your handling code here:
        int res;
        res = JOptionPane.showConfirmDialog(this, "Are You sure to exit?");
        System.out.println(res);
        if (res == 0){
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
    }//GEN-LAST:event_txtproductActionPerformed

    private void lblexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexitMouseClicked
        // TODO add your handling code here:
         int res;
        res = JOptionPane.showConfirmDialog(this, "Are You sure to exit?");
        System.out.println(res);
        if (res == 0){
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
    }//GEN-LAST:event_lblexitMouseClicked

    private void lblsignoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsignoutMouseClicked
        // TODO add your handling code here:
        welcome we = new welcome();
        int res;
        res = JOptionPane.showConfirmDialog(this, "Are you sure to Logout?" );
        switch (res) {
            case 0:
                
                we.setVisible(true);   
                this.setVisible(false);     
                break;
            default:
                break;
        }
    }//GEN-LAST:event_lblsignoutMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
   if(!"".equals(txtproduct.getText()) && !"".equals(txtprice.getText()) && !"".equals(txtquantity.getText())){
            setData();
   }
          else{
            JOptionPane.showMessageDialog(this, "Please Fill all fields.");}
         
    }//GEN-LAST:event_jLabel3MouseClicked

    private void dashboardbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardbtnMouseClicked
       adminboard ad = new adminboard();
       ad.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_dashboardbtnMouseClicked
   
        
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addproduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel categorylbl;
    private javax.swing.JComboBox<String> cbcategory;
    private javax.swing.JLabel dashboardbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblexit;
    private javax.swing.JLabel lblquantity;
    private javax.swing.JLabel lblquantity1;
    private javax.swing.JLabel lblsignout;
    private javax.swing.JLabel productname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtproduct;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JLabel unitprice;
    // End of variables declaration//GEN-END:variables
}
