/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loginpage;

import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Nusrat Ali
 */
public class manageproduct extends javax.swing.JFrame {
    manageproductBll mpb = new manageproductBll();
    ManageProductDao mpd = new ManageProductDaoImpl();
    /**
     * Creates new form manageproduct
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblexit = new javax.swing.JLabel();
        lblsignout = new javax.swing.JLabel();
        dashboardbtn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        productnamelbl = new javax.swing.JLabel();
        txtproduct = new javax.swing.JTextField();
        productidlbl = new javax.swing.JLabel();
        txtproductid = new javax.swing.JTextField();
        editbtn = new javax.swing.JLabel();
        submitbtn = new javax.swing.JLabel();
        removebtn = new javax.swing.JLabel();
        newproductlbl = new javax.swing.JLabel();
        newproducttxt = new javax.swing.JTextField();
        quantitylbl = new javax.swing.JLabel();
        quantitytxt = new javax.swing.JTextField();
        l = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jPanel1.setOpaque(false);

        lblexit.setBackground(new java.awt.Color(0, 96, 50));
        lblexit.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblexit.setForeground(new java.awt.Color(255, 255, 255));
        lblexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblexit.setText("Exit");
        lblexit.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 153, 51), null));
        lblexit.setOpaque(true);
        lblexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblexitMouseClicked(evt);
            }
        });

        lblsignout.setBackground(new java.awt.Color(0, 96, 50));
        lblsignout.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblsignout.setForeground(new java.awt.Color(255, 255, 255));
        lblsignout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsignout.setText("Sign Out");
        lblsignout.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 153, 51), null));
        lblsignout.setOpaque(true);
        lblsignout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsignoutMouseClicked(evt);
            }
        });

        dashboardbtn.setBackground(new java.awt.Color(0, 96, 50));
        dashboardbtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        dashboardbtn.setForeground(new java.awt.Color(255, 255, 255));
        dashboardbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardbtn.setText("Dashboard");
        dashboardbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 102, 51), null));
        dashboardbtn.setOpaque(true);
        dashboardbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lblsignout, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblexit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsignout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblexit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboardbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 510, 210));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel2.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage Products");
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 11, 296, -1));

        productnamelbl.setBackground(java.awt.Color.darkGray);
        productnamelbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        productnamelbl.setForeground(new java.awt.Color(255, 255, 255));
        productnamelbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        productnamelbl.setText("Product Name");
        productnamelbl.setOpaque(true);
        jPanel2.add(productnamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 106, 172, 35));

        txtproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductActionPerformed(evt);
            }
        });
        jPanel2.add(txtproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 109, 189, 35));

        productidlbl.setBackground(java.awt.Color.darkGray);
        productidlbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        productidlbl.setForeground(new java.awt.Color(255, 255, 255));
        productidlbl.setText("Product ID");
        productidlbl.setOpaque(true);
        jPanel2.add(productidlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, 172, 32));
        jPanel2.add(txtproductid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 189, 32));

        editbtn.setBackground(new java.awt.Color(0, 96, 50));
        editbtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        editbtn.setForeground(new java.awt.Color(255, 255, 255));
        editbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editbtn.setText("Edit");
        editbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 102, 51), null));
        editbtn.setOpaque(true);
        editbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editbtnMouseClicked(evt);
            }
        });
        jPanel2.add(editbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 121, 42));

        submitbtn.setBackground(new java.awt.Color(0, 96, 50));
        submitbtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        submitbtn.setForeground(new java.awt.Color(255, 255, 255));
        submitbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        submitbtn.setText("Submit");
        submitbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 102, 51), null));
        submitbtn.setOpaque(true);
        submitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitbtnMouseClicked(evt);
            }
        });
        jPanel2.add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 386, 124, 43));

        removebtn.setBackground(new java.awt.Color(0, 96, 50));
        removebtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        removebtn.setForeground(new java.awt.Color(255, 255, 255));
        removebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removebtn.setText("Remove");
        removebtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 102, 51), null));
        removebtn.setOpaque(true);
        removebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removebtnMouseClicked(evt);
            }
        });
        jPanel2.add(removebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 386, 124, 42));

        newproductlbl.setBackground(java.awt.Color.darkGray);
        newproductlbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        newproductlbl.setForeground(new java.awt.Color(255, 255, 255));
        newproductlbl.setText("New Product Name");
        newproductlbl.setOpaque(true);
        jPanel2.add(newproductlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, 192, 32));

        newproducttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newproducttxtActionPerformed(evt);
            }
        });
        jPanel2.add(newproducttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 189, 32));

        quantitylbl.setBackground(java.awt.Color.darkGray);
        quantitylbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        quantitylbl.setForeground(new java.awt.Color(255, 255, 255));
        quantitylbl.setText("Quantity");
        quantitylbl.setOpaque(true);
        jPanel2.add(quantitylbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 299, 192, 32));

        quantitytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitytxtActionPerformed(evt);
            }
        });
        jPanel2.add(quantitytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 190, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 480, 460));

        l.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nusrat Ali\\Desktop\\download (2).jfif")); // NOI18N
        getContentPane().add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -150, 680, 1110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductActionPerformed
        // TODO add your handling code here:
        int res;
        res = JOptionPane.showConfirmDialog(this, "Are You sure to exit?");
        System.out.println(res);
        if (res == 0){
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
    }//GEN-LAST:event_txtproductActionPerformed
public void editproduct(){
       productnamelbl.setVisible(true);
       quantitylbl.setVisible(true);
       newproducttxt.setVisible(true);
       quantitytxt.setVisible(true);
       submitbtn.setVisible(true);
       txtproductid.setVisible(false);
       removebtn.setVisible(false);
       productidlbl.setVisible(true);
       editbtn.setVisible(false);
       productnamelbl.setVisible(false);
      txtproduct.setVisible(false);
       mpb.setProductName(productnamelbl.getText());
      
    }

    private void lblsignoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsignoutMouseClicked
        welcome we = new welcome();
        int res;
        res = JOptionPane.showConfirmDialog(this, "Are you sure to Logout?" );
        switch (res) {
            case 0:

            we.setVisible(true);    //opens the LoginType Jframe.
            this.setVisible(false);     //closes the current JFrame form.
            break;
            //this.setVisible(true);
            default:
            break;
        }
    }//GEN-LAST:event_lblsignoutMouseClicked

    private void lblexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexitMouseClicked
        // TODO add your handling code here:
        int res;
        res = JOptionPane.showConfirmDialog(this, "Are You sure to exit?");
        System.out.println(res);
        if (res == 0){
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
    }//GEN-LAST:event_lblexitMouseClicked

    private void editbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbtnMouseClicked
        editproduct();
    }//GEN-LAST:event_editbtnMouseClicked
    
    private void removebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removebtnMouseClicked
        mpb.setProductName(productnamelbl.getText());
        int res = JOptionPane.showConfirmDialog(this, "Are you sure to remove the product?");
        if(res == 0){
        mpd.removeProduct(mpb);
        JOptionPane.showMessageDialog(this, "Product Removed Successfully.");
        txtproduct.setText(null);
        
        }
        else{
            txtproduct.setText(null);
        
        }
    }//GEN-LAST:event_removebtnMouseClicked
        
    private void submitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitbtnMouseClicked
        mpb.setNewProdName(newproducttxt.getText());
        mpb.setNewQuantity(quantitytxt.getText());
        mpd.editProduct(mpb);
        JOptionPane.showMessageDialog(this, "Product Edited Successfully.");      
    }//GEN-LAST:event_submitbtnMouseClicked
    public manageproduct() {
        initComponents();
      newproductlbl.setVisible(false);
       quantitylbl.setVisible(false);
       newproducttxt.setVisible(false);
       quantitytxt.setVisible(false);
       submitbtn.setVisible(false);
       
    }
    private void newproducttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newproducttxtActionPerformed
    }//GEN-LAST:event_newproducttxtActionPerformed

    private void quantitytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitytxtActionPerformed
    }//GEN-LAST:event_quantitytxtActionPerformed

    private void dashboardbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardbtnMouseClicked
        adminboard ad = new adminboard();
        ad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardbtnMouseClicked
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageproduct().setVisible(true);
            }
        });
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardbtn;
    private javax.swing.JLabel editbtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l;
    private javax.swing.JLabel lblexit;
    private javax.swing.JLabel lblsignout;
    private javax.swing.JLabel newproductlbl;
    private javax.swing.JTextField newproducttxt;
    private javax.swing.JLabel productidlbl;
    private javax.swing.JLabel productnamelbl;
    private javax.swing.JLabel quantitylbl;
    private javax.swing.JTextField quantitytxt;
    private javax.swing.JLabel removebtn;
    private javax.swing.JLabel submitbtn;
    private javax.swing.JTextField txtproduct;
    private javax.swing.JTextField txtproductid;
    // End of variables declaration//GEN-END:variables
}
