/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loginpage;

import java.awt.Dimension;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.ImageObserver;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.MessageFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;


/**
 *
 * @author Nusrat Ali
 */
public class orderproduct extends javax.swing.JFrame {

    /**
     * Creates new form orderproduct
     */
    public orderproduct() {
        initComponents();
    }
String totalprice;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        orderproductlbl = new javax.swing.JLabel();
        fruitscb = new javax.swing.JComboBox<>();
        vegetablescb = new javax.swing.JComboBox<>();
        spicescb = new javax.swing.JComboBox<>();
        otherproductsbtn = new javax.swing.JComboBox<>();
        cartbtn = new javax.swing.JButton();
        lblexit = new javax.swing.JLabel();
        gobacklbl = new javax.swing.JLabel();
        vegetablespin = new javax.swing.JSpinner();
        fruitsspin = new javax.swing.JSpinner();
        spicesspin = new javax.swing.JSpinner();
        otherspinner = new javax.swing.JSpinner();
        fruitskglbl = new javax.swing.JLabel();
        kglbl1 = new javax.swing.JLabel();
        boxlbl = new javax.swing.JLabel();
        otherprdctslbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        orderproductlbl.setBackground(new java.awt.Color(51, 102, 0));
        orderproductlbl.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        orderproductlbl.setForeground(new java.awt.Color(255, 255, 255));
        orderproductlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderproductlbl.setText("Order products");
        orderproductlbl.setOpaque(true);

        fruitscb.setBackground(new java.awt.Color(204, 204, 255));
        fruitscb.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        fruitscb.setForeground(new java.awt.Color(0, 102, 51));
        fruitscb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fruits", "Mango", "Apple", "Banana", "Peach", "Watermelon", "Sweet melon", "Grapes" }));

        vegetablescb.setBackground(new java.awt.Color(204, 204, 255));
        vegetablescb.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        vegetablescb.setForeground(new java.awt.Color(0, 102, 51));
        vegetablescb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vegetables", "Potates", "Tomates", "Onion", "Ginger", "Carrot" }));
        vegetablescb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegetablescbActionPerformed(evt);
            }
        });

        spicescb.setBackground(new java.awt.Color(204, 204, 255));
        spicescb.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        spicescb.setForeground(new java.awt.Color(0, 102, 51));
        spicescb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Spices", "Black pepper", "Chilli powder", "Cinnamon", "Cloves", "Salt" }));
        spicescb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spicescbActionPerformed(evt);
            }
        });

        otherproductsbtn.setBackground(new java.awt.Color(204, 204, 255));
        otherproductsbtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        otherproductsbtn.setForeground(new java.awt.Color(0, 102, 51));
        otherproductsbtn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Other Products", "Butter", "Sugar", "Jam", "Cheese", "Black Sauce" }));
        otherproductsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherproductsbtnActionPerformed(evt);
            }
        });

        cartbtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        cartbtn.setForeground(new java.awt.Color(0, 102, 0));
        cartbtn.setText("Show Bill");
        cartbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        cartbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartbtnMouseClicked(evt);
            }
        });
        cartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartbtnActionPerformed(evt);
            }
        });

        lblexit.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        lblexit.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        lblexit.setForeground(new java.awt.Color(0, 102, 51));
        lblexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblexit.setText("Exit");
        lblexit.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 102, 51), null));
        lblexit.setOpaque(true);
        lblexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblexitMouseClicked(evt);
            }
        });

        gobacklbl.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        gobacklbl.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        gobacklbl.setForeground(new java.awt.Color(0, 102, 51));
        gobacklbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gobacklbl.setText("Go Back");
        gobacklbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 102, 51), null));
        gobacklbl.setOpaque(true);
        gobacklbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gobacklblMouseClicked(evt);
            }
        });

        vegetablespin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        fruitsspin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        spicesspin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        otherspinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        fruitskglbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        fruitskglbl.setForeground(new java.awt.Color(0, 51, 255));
        fruitskglbl.setText("KG");
        fruitskglbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 102, 255), null));
        fruitskglbl.setOpaque(true);

        kglbl1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        kglbl1.setForeground(new java.awt.Color(0, 51, 255));
        kglbl1.setText("KG");
        kglbl1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 102, 255), null));
        kglbl1.setOpaque(true);

        boxlbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        boxlbl.setForeground(new java.awt.Color(0, 51, 255));
        boxlbl.setText("Box");
        boxlbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 102, 255), null));
        boxlbl.setOpaque(true);

        otherprdctslbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        otherprdctslbl.setForeground(new java.awt.Color(0, 51, 255));
        otherprdctslbl.setText("Bottle/box");
        otherprdctslbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 102, 255), null));
        otherprdctslbl.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fruitscb, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fruitsspin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(vegetablescb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vegetablespin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fruitskglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kglbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblexit, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gobacklbl, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(orderproductlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(otherproductsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(196, 196, 196)
                                .addComponent(otherspinner, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(spicescb, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spicesspin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(otherprdctslbl)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cartbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(orderproductlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vegetablespin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fruitskglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vegetablescb, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fruitscb, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fruitsspin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kglbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spicescb, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spicesspin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(otherspinner, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(otherprdctslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addComponent(cartbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(otherproductsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gobacklbl, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblexit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 610, 620));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nusrat Ali\\Desktop\\gre.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, 720, 970));

        setBounds(0, 0, 728, 709);
    }// </editor-fold>//GEN-END:initComponents

    private void vegetablescbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegetablescbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vegetablescbActionPerformed

    private void spicescbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spicescbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spicescbActionPerformed

    private void otherproductsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherproductsbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherproductsbtnActionPerformed

   
public int price(){
    int vege = (int) vegetablespin.getValue();
    int vegeprice = vege*50;
    int fruits = (int) fruitsspin.getValue();
    int fruitsprice = fruits*70;
    int spices = (int) spicesspin.getValue();
    int spicesprice = vege*100;
    int otherprod = (int) otherspinner.getValue();
    int productsprice = vege*120;
    int totalprice = vegeprice + fruitsprice + spicesprice + productsprice;
    return totalprice;
}


    private void cartbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartbtnMouseClicked
    
        int p= price();
        if (p>1000){
            p = (p - 50);
        JOptionPane.showMessageDialog(this, "CART " 
                + System.lineSeparator()+ "-----------------------------"+
                 System.lineSeparator()+
                vegetablescb.getSelectedItem()+"                "+ vegetablespin.getValue() +
                System.lineSeparator()+
                "-----------------------------"+ System.lineSeparator()+
                fruitscb.getSelectedItem() +"                   "+ fruitsspin.getValue() +
                System.lineSeparator()+
                "---------------------------- "+ System.lineSeparator()
                +spicescb.getSelectedItem()+ "                  "+ spicesspin.getValue()
                + System.lineSeparator()+
                "---------------------------"+  System.lineSeparator()+
                otherproductsbtn.getSelectedItem() +"           "+ otherspinner.getValue() +
                System.lineSeparator()+
                "-----------------------------"+ System.lineSeparator()+
                "You are awarded with 50 per discount" + p);
               }
        else{  JOptionPane.showMessageDialog(this, "CART " 
                + System.lineSeparator()+ "-----------------------------"+
                 System.lineSeparator()+
                vegetablescb.getSelectedItem()+"                "+ vegetablespin.getValue() +
                System.lineSeparator()+
                "-----------------------------"+ System.lineSeparator()+
                fruitscb.getSelectedItem() +"                   "+ fruitsspin.getValue() +
                System.lineSeparator()+
                "---------------------------- "+ System.lineSeparator()
                +spicescb.getSelectedItem()+ "                  "+ spicesspin.getValue()
                + System.lineSeparator()+
                "---------------------------"+  System.lineSeparator()+
                otherproductsbtn.getSelectedItem() +"           "+ otherspinner.getValue() +
                System.lineSeparator()+
                "-----------------------------"+ System.lineSeparator()+
                "Your total bill is " + price());
            }
    }//GEN-LAST:event_cartbtnMouseClicked

    private void lblexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexitMouseClicked
        int res;
        res = JOptionPane.showConfirmDialog(this, "Are You sure to exit?");
        System.out.println(res);
        if (res == 0){  
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));        // TODO add your handling code here:
    }//GEN-LAST:event_lblexitMouseClicked
    }
    private void cartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartbtnActionPerformed
      
    }//GEN-LAST:event_cartbtnActionPerformed

    private void gobacklblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobacklblMouseClicked
        userdashboard ud = new userdashboard();
        ud.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_gobacklblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orderproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orderproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orderproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orderproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orderproduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boxlbl;
    private javax.swing.JButton cartbtn;
    private javax.swing.JComboBox<String> fruitscb;
    private javax.swing.JLabel fruitskglbl;
    private javax.swing.JSpinner fruitsspin;
    private javax.swing.JLabel gobacklbl;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel kglbl1;
    private javax.swing.JLabel lblexit;
    private javax.swing.JLabel orderproductlbl;
    private javax.swing.JLabel otherprdctslbl;
    private javax.swing.JComboBox<String> otherproductsbtn;
    private javax.swing.JSpinner otherspinner;
    private javax.swing.JComboBox<String> spicescb;
    private javax.swing.JSpinner spicesspin;
    private javax.swing.JComboBox<String> vegetablescb;
    private javax.swing.JSpinner vegetablespin;
    // End of variables declaration//GEN-END:variables
}
